spring.application.name=MedicalAppointmentBookingSystem
server.port=8080
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MABS;encrypt=true;trustServerCertificate=true
# Database connection properties
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#Hibernate properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
#Template engine
spring.thymleaf.prefix=classpath:/templates/
spring.thymleaf.suffix=.html
spring.thymleaf.mode=HTML
spring.thymleaf.cache=false
#Nếu session bị đóng thì sẽ không thể truy cập vào database nữa, nên tắt tính năng này để tránh lỗi LazyInitializationException
spring.jpa.open-in-view=false
#Account sample
spring.security.user.name=admin
spring.security.user.password=123
spring.security.user.roles=ADMIN

# CLOUDINARY CONFIGURATION
cloudinary.cloud-name=dp18ydfj9
cloudinary.api-key=935372985876969
# API Secret from Cloudinary:
cloudinary.api-secret=YOUR_API_SECRET_HERE

